package consts

const (
	PLAYER_HEALTH        = 90
	PLAYER_SCALE         = 0.1
	PLAYER_HITBOX_OFFSET = 25
	VELOCITY_PER_FRAME   = 5
	MAX_VELOCITY         = 100
	RECOIL_FRAMES        = 30
	RECOIL_VELOCITY      = -130

	BULLET_DAMAGE        = 30
	BULLET_SCALE         = 0.1
	BULLET_HITBOX_OFFSET = 25
	BULLET_LIFESPAN      = 10

	ASTEROID_HEALTH        = 90
	ASTEROID_MIN_MASS      = 30
	ASTEROID_MASS_VAR      = 21
	ASTEROID_SCALE         = 0.05
	ASTEROID_HITBOX_OFFSET = 12.5
	ASTEROID_DAMAGE        = 15
)
